import { ArrowUpRight } from 'lucide-react';
import { CATEGORY_LINKS, gygCategoryHref } from '../../../shared/gyg/picks';
import { useLocale } from '../i18n/useLocale';

/**
 * Direct GetYourGuide category links — generated by
 * scripts/gyg-rollout.mjs on 2026-07-30. Edit the generator, not this file.
 *
 * This site gets category links rather than product cards on purpose: the
 * GetYourGuide supply does not honestly match what the site promises, so naming
 * four specific tours would invent relevance. The reasoning is in picks.ts.
 *
 * Price IS rendered on the product-card sites, but never as ours: it is GetYourGuide's own
 * "from" price on GYG_PRICE_AS_OF, printed with the source and that date beside
 * it. Euros — an earlier note in this codebase claimed USD, which was wrong and
 * came from a JSON-LD field the crawler never stored. No "per person" label:
 * the catalogue does not record the unit and some products are priced per group.
 *
 * Ratings and review counts stay out. We cannot keep them current, and a stale
 * "4.6 (869)" is a claim about other people's experience, not a fact.
 */

const COPY = {
  "kicker": {
    "en": "Book now",
    "fi": "Varaa heti",
    "de": "Jetzt buchen",
    "ja": "今すぐ予約",
    "es": "Reserva ya",
    "pt-BR": "Reserve agora",
    "zh-CN": "立即预订",
    "ko": "지금 예약",
    "fr": "Réservez",
    "it": "Prenota ora",
    "nl": "Boek nu",
    "sv": "Boka nu"
  },
  "ctaProduct": {
    "en": "Check availability",
    "fi": "Katso saatavuus",
    "de": "Verfügbarkeit prüfen",
    "ja": "空き状況を見る",
    "es": "Ver disponibilidad",
    "pt-BR": "Ver disponibilidade",
    "zh-CN": "查看可订日期",
    "ko": "예약 가능 여부 확인",
    "fr": "Voir les disponibilités",
    "it": "Vedi disponibilità",
    "nl": "Bekijk beschikbaarheid",
    "sv": "Se tillgänglighet"
  },
  "ctaCategory": {
    "en": "Browse all",
    "fi": "Selaa kaikki",
    "de": "Alle ansehen",
    "ja": "すべて見る",
    "es": "Ver todo",
    "pt-BR": "Ver tudo",
    "zh-CN": "查看全部",
    "ko": "전체 보기",
    "fr": "Voir tout",
    "it": "Vedi tutto",
    "nl": "Bekijk alles",
    "sv": "Se alla"
  },
  "via": {
    "en": "via GetYourGuide",
    "fi": "GetYourGuiden kautta",
    "de": "über GetYourGuide",
    "ja": "GetYourGuide 経由",
    "es": "con GetYourGuide",
    "pt-BR": "via GetYourGuide",
    "zh-CN": "通过 GetYourGuide",
    "ko": "GetYourGuide 제공",
    "fr": "via GetYourGuide",
    "it": "tramite GetYourGuide",
    "nl": "via GetYourGuide",
    "sv": "via GetYourGuide"
  },
  "priceFrom": {
    "en": "from",
    "fi": "alkaen",
    "de": "ab",
    "ja": "〜より",
    "es": "desde",
    "pt-BR": "a partir de",
    "zh-CN": "起价",
    "ko": "부터",
    "fr": "à partir de",
    "it": "da",
    "nl": "vanaf",
    "sv": "från"
  },
  "priceSource": {
    "en": "Price on GetYourGuide",
    "fi": "Hinta GetYourGuidessa",
    "de": "Preis auf GetYourGuide",
    "ja": "GetYourGuide の価格",
    "es": "Precio en GetYourGuide",
    "pt-BR": "Preço no GetYourGuide",
    "zh-CN": "GetYourGuide 价格",
    "ko": "GetYourGuide 가격",
    "fr": "Prix sur GetYourGuide",
    "it": "Prezzo su GetYourGuide",
    "nl": "Prijs op GetYourGuide",
    "sv": "Pris på GetYourGuide"
  },
  "headingProduct": {
    "en": "Bookable today",
    "fi": "Varattavissa tänään",
    "de": "Heute buchbar",
    "ja": "今日予約できる体験",
    "es": "Reservable hoy",
    "pt-BR": "Reservável hoje",
    "zh-CN": "今天即可预订",
    "ko": "오늘 예약 가능",
    "fr": "Réservable aujourd’hui",
    "it": "Prenotabile oggi",
    "nl": "Vandaag te boeken",
    "sv": "Bokningsbart i dag"
  },
  "ledeProduct": {
    "en": "Hand-picked food and drink experiences, bookable online through GetYourGuide.",
    "fi": "Poimitut ruoka- ja juomaelämykset — varattavissa verkossa GetYourGuiden kautta.",
    "de": "Ausgewählte Essens- und Getränkeerlebnisse — online über GetYourGuide buchbar.",
    "ja": "厳選したフード＆ドリンク体験。GetYourGuide でオンライン予約できます。",
    "es": "Experiencias de comida y bebida seleccionadas, reservables en línea con GetYourGuide.",
    "pt-BR": "Experiências de comida e bebida selecionadas, reserváveis online via GetYourGuide.",
    "zh-CN": "精选美食与饮品体验，可通过 GetYourGuide 在线预订。",
    "ko": "엄선한 음식·음료 체험 — GetYourGuide에서 온라인 예약.",
    "fr": "Une sélection d'expériences culinaires, réservables en ligne via GetYourGuide.",
    "it": "Esperienze di cibo e bevande selezionate, prenotabili online tramite GetYourGuide.",
    "nl": "Geselecteerde eet- en drinkervaringen, online te boeken via GetYourGuide.",
    "sv": "Utvalda mat- och dryckesupplevelser — bokas online via GetYourGuide."
  },
  "headingCategory": {
    "en": "Browse and book on GetYourGuide",
    "fi": "Selaa ja varaa GetYourGuidessa",
    "de": "Auf GetYourGuide stöbern und buchen",
    "ja": "GetYourGuide で探して予約",
    "es": "Explora y reserva en GetYourGuide",
    "pt-BR": "Explore e reserve no GetYourGuide",
    "zh-CN": "在 GetYourGuide 浏览并预订",
    "ko": "GetYourGuide에서 둘러보고 예약",
    "fr": "Parcourez et réservez sur GetYourGuide",
    "it": "Sfoglia e prenota su GetYourGuide",
    "nl": "Bekijk en boek op GetYourGuide",
    "sv": "Bläddra och boka på GetYourGuide"
  },
  "ledeCategory": {
    "en": "A partner-maintained list, always current — we do not name a single tour here.",
    "fi": "Kumppanin ylläpitämä lista, aina ajantasainen — emme nimeä yksittäistä retkeä.",
    "de": "Eine vom Partner gepflegte Liste, immer aktuell.",
    "ja": "パートナーが管理する最新のリストです。",
    "es": "Una lista mantenida por el socio, siempre actualizada.",
    "pt-BR": "Uma lista mantida pelo parceiro, sempre atual.",
    "zh-CN": "由合作伙伴维护的列表，始终保持最新。",
    "ko": "파트너가 관리하는 항상 최신 목록입니다.",
    "fr": "Une liste tenue à jour par le partenaire.",
    "it": "Un elenco aggiornato dal partner.",
    "nl": "Een door de partner bijgehouden, actuele lijst.",
    "sv": "En lista som partnern håller uppdaterad."
  }
};

export default function GygPicks() {
  const { locale: lang } = useLocale();
  const t = (m: Record<string, string>): string => m[lang] ?? m.en;
  const L = COPY;
  const rows = CATEGORY_LINKS['laplandfood-new'] ?? [];

const CAT_LABEL: Record<string, Record<string, string>> = {
  'ski-snowboard-tc146':      { en: 'Ski & snowboard', fi: 'Hiihto ja lumilautailu' },
  'snow-winter-sports-tc113': { en: 'Snow & winter sports', fi: 'Talviurheilu' },
  'food-drinks-tc103':        { en: 'Food & drinks', fi: 'Ruoka ja juoma' },
  'dinner-packages-tc100':    { en: 'Dinner packages', fi: 'Illalliskokonaisuudet' },
  'airport-transfers-tc153':  { en: 'Airport transfers', fi: 'Lentokenttäkuljetukset' },
  'transfers-tc152':          { en: 'Transfers', fi: 'Kuljetukset' },
};
const catName = (path: string, lang: string): string => {
  const key = path.split('/').pop() ?? '';
  const m = CAT_LABEL[key];
  return m ? (m[lang] ?? m.en) : key.replace(/-tc\d+$/, '').replace(/-/g, ' ');
};

  if (!rows.length) return null;

  return (
    <section className="py-16 sm:py-20 px-4 sm:px-6 bg-transparent">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10 sm:mb-12">
          <p className="font-bold tracking-[0.18em] uppercase text-sm mb-3 text-[#BE185D]">{t(L.kicker)}</p>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 text-[#0F172A]">
            {t(L.headingCategory)}
          </h2>
          <p className="max-w-2xl text-black/65">{t(L.ledeCategory)}</p>
        </div>

        <div className="grid gap-5 sm:grid-cols-2">
        {rows.map((c) => (
          <a
            key={c.path}
            href={gygCategoryHref(c, lang)}
            target="_blank"
            rel="sponsored nofollow noopener"
            className="group flex flex-col rounded-2xl border bg-white border-black/10 shadow-sm p-6 no-underline transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:border-[#BE185D]/40"
          >
            <h3 className="flex-1 text-lg font-bold leading-snug text-[#0F172A]">{catName(c.path, lang)}</h3>

            <span className="mt-5 inline-flex items-center justify-center gap-2 rounded-full bg-[#DB2777] px-5 py-2.5 text-sm font-bold text-white transition-opacity group-hover:opacity-90">
              {t(L.ctaCategory)}
              <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
            </span>

            <span className="mt-2 text-center text-[11px] uppercase tracking-[0.12em] text-black/55">{t(L.via)}</span>
          </a>
        ))}
        </div>
      </div>
    </section>
  );
}
